[package]
name = "curseofrust-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
curseofrust = { path = ".." }
cli-parser = { path = "../cli", package = "curseofrust-cli-parser" }