[package]
name = "curseofrust-msg"
version = "0.1.0"
edition = "2021"
authors = ["Jiening Yu <jiening.yu@outlook.com>"]
description = "Curseofwar messaging protocol implementation"
repository = "https://codeberg.org/DM-Earth/curseofrust"
license = "AGPL-3.0-or-later"
keywords = []
categories = ["game-development"]

[dependencies]
curseofrust = { path = "../" }
bytemuck = "1.21"
