[package]
name = "curseofrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "2.1.0"

[workspace]
resolver = "2"
members = ["gui-cocoa", "console", "cli", "msg", "ffi"]

[profile.release]
panic = "abort"
lto = "fat"
