[package]
name = "curseofrust-gui-cocoa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curseofrust = { path = ".." }
build-time = "0.1.3"
fastrand = "2.0"
cli-parser = { path = "../cli", package = "curseofrust-cli-parser" }

[target.'cfg(target_os = "macos")'.dependencies]
cacao = "0.3.2"
dispatch = "0.2.0"
