[package]
name = "curseofrust-cli-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curseofrust = { path = ".." }
clap_lex = "0.7.1"

[features]
net-proto = []
