[package]
name = "curseofrust-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curseofrust = { path = ".." }
curseofrust-cli-parser = { path = "../cli" }
curseofrust-msg = { path = "../msg" }
futures-lite = "2.3.0"
async-executor = "1.12"
async-io = "2.3"
fastrand = "2.1.0"
local-ip-address = "0.6"

[features]
