[package]
name = "curseofrust-server"
version = "0.1.0"
edition = "2021"
authors = ["Jiening Yu <jiening.yu@outlook.com>"]
description = "Server binary of curseofrust"
repository = "https://codeberg.org/DM-Earth/curseofrust"
license = "AGPL-3.0-or-later"
keywords = []
categories = ["games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curseofrust = "0.1"
curseofrust-cli-parser = { version = "0.1", features = ["net-proto"] }
curseofrust-msg = "0.1"
curseofrust-net-foundation = "0.1"
futures-lite = "2.6"
async-io = "2.4"
async-executor = "1.13"
fastrand = "2.3"
local-ip-address = "0.6"

[features]
ws = ["curseofrust-net-foundation/ws"]
