[package]
name = "curseofrust-console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curseofrust = { path = ".." }
curseofrust-cli-parser = { path = "../cli" }
curseofrust-msg = { path = "../msg", optional = true }
fastrand = "2.1.0"
crossterm = { version = "0.27", features = ["event-stream"] }
futures-lite = "2.3.0"
async-io = "2.3"

[features]
multiplayer = ["dep:curseofrust-msg"]
