[package]
name = "curseofrust-console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curseofrust = { path = ".." }
curseofrust-cli-parser = { path = "../cli" }
fastrand = "2.1.0"
crossterm = { version = "0.27", features = ["event-stream"] }
futures-lite = "2.3.0"
async-io = "2.3"
curseofrust-msg = { path = "../msg", optional = true }
async-executor = { version = "1.12", optional = true }
local-ip-address = { version = "0.6", optional = true }

[features]
default = ["multiplayer"]
multiplayer = [
  "dep:curseofrust-msg",
  "dep:local-ip-address",
  "dep:async-executor"
]
