[package]
name = "curseofrust-console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curseofrust = { path = ".." }
curseofrust-cli-parser = { path = "../cli" }
fastrand = "2.0"
crossterm = { version = "0.27", features = ["event-stream"] }
futures-lite = "2.2"
async-io = "2.3"
