[package]
name = "curseofrust-net-foundation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unisock = { git = "https://codeberg.org/DM-Earth/unisock.git", branch = "main", package = "unisock" }
unisock-smol = { git = "https://codeberg.org/DM-Earth/unisock.git", branch = "main", package = "unisock-smol" }
unisock-smol-tungstenite = { git = "https://codeberg.org/DM-Earth/unisock.git", branch = "main", package = "unisock-smol-tungstenite" }

[features]
